# sample-config.yaml
# EDIT ME!

# options: dev or prod
active_env: "dev"

dev:
  domain: "http://10.8.0.197:8000/api/v1"
  cred_file: "dev.cred"

  # pull in reference info from SnipeIT
  reference_script: "pull-ids.py"
  reference_json: "snipeit_reference_ids.json"
  
  #model to find or create:
  target_model_name: "testing-model-0"
  target_status_name: "Deployed" #status tag for the asset

  #test points if model isn't known: 
  default_category_name: "Laptop" 
  default_manufacturer_name: "Lenovo"

  asset_count: 3 #number of assets with this model

  #TODO: update to take category and manufacture names
# Better TODO: setup file call to all specs, populate based on
# Manufacturer/model from spec call...

# prod:
#   domain: "https://snipeit.camio.acep.uaf.edu//api/v1"
#   cred_file: "prod.cred"

#   target_model_name: ""
  
